### PR TITLE
Attempt to load PySide2 if PyQt5 does not exist

### PR DESCRIPTION
**Pull request by fredrikaverpil**
This will attempt to load PySide2 if PyQt5 fails to load. It can serve as the base for early testing with PySide2 although, down the line we might want to explicitly define which binding to use.

### CODE REVIEW

**Comment by fredrikaverpil** [comment]
I noticed that you're using tabs to indent your code. I personally prefer spaces and use this everywhere. Even PEP8 recommends spaces instead of tabs.

I believe Python 3 is more picky about mixing spaces and tabs and won't accept such mixing without raising errors (not entirely sure here). Since this is an open source project, perhaps I can persuade you to follow the PEP8 recommendations and use (4) spaces instead of a tab? 😉

**Comment by fredrikaverpil** [comment]
I might just add that I successfully ran and froze the tutorial apps on macOS like this:

```bash
conda config --add channels conda-forge
conda create -n fbs_pyside2 python=3.5 pyside2
source activate fbs_pyside2
pip install -r requirements.txt
pip -m fbs run
pip -m fbs freeze
```

**Comment by fredrikaverpil** [comment]
Just adding this also works on Windows with the patches applied:

- #1  
- #4 
- #5

**Comment by mherrmann** [comment]
Thanks for this as well. Because of the tabs/spaces problem, I simply applied the changes manually to have a cleaner commit. Closing this PR and continuing the discussion in #4 and #5.

**Pull request closed without merging**
