### PR TITLE
Exclude Module Config Added

### PR DESCRIPTION
**Pull request by luigifreitas**
Add the ability to list modules to be excluded when freezing with PyInstaller. #90

### CODE REVIEW

**Comment by mherrmann** [comment]
Thank you for the PR. I think I would enable this via a new `extra_pyinstaller_args` setting. See [here](https://github.com/mherrmann/fbs/pull/157#issuecomment-562086353). I don't have time to work on this right now, but hopefully again in February.

**Comment by luigifreitas** [comment]
@mherrmann I reverted this PR to the initial state and implemented the [specified changes](https://github.com/mherrmann/fbs/pull/157#issuecomment-562086353) for passing arbitrary PyInstaller arguments. Tested with the latest version of PyInstaller.

**Comment by mherrmann** [comment]
Thanks. The changes look good to me but I need to update the documentation as well and release a new version. I'll look at this in February.

**Comment by mherrmann** [comment]
I now released this in [fbs 0.8.9](https://github.com/mherrmann/fbs/releases/tag/v0.8.9). Thanks!

**Pull request closed without merging**
